---
title: "CRISIS_Factor_Pipeline CFA Adaptive Func 2 weeks 3/25"
author: "Aki Nikolaidis, Paul Bloom, Michelle VanTieghem"
date: "3/25/21"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---
Edited by BV and JD 8/25/20 for CRISIS AFAR

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

```{r, message = F}
library(tidyverse)
library(ggplot2)
library(viridis)
library(readxl)
library(corrplot)
library(knitr)
library(REdaS) # for diagnostic data checks before FA
library(psych)# need for factor analysis
library(GPArotation) # need for factor analysis
library(polycor)
library(lavaan)
library(sjmisc)

```


## CONFIRMATORY FACTOR ANALYSIS

# Adaptive Functioning
```{r}
All_Site_Combo <- read.csv("03_25_Merged_Splits_across_All_sites.csv" , header = TRUE, sep = ",")

#rescaling
All_Site_Combo <- All_Site_Combo %>%
  mutate(playentertain_2= ifelse(playentertain_2== 5, 1,
                                 ifelse(playentertain_2== 6, 2,
                                        ifelse(playentertain_2==7, 3,
                                               ifelse(playentertain_2==8, 4, 
                                                      ifelse(playentertain_2==1, 1,
                                                             ifelse(playentertain_2==2,2,
                                                                    ifelse(playentertain_2 ==3, 3,
                                                                           ifelse(playentertain_2 ==4,4, "check")))))))))

All_Site_Combo$playentertain_2 <- as.numeric(playentertain_2)

domain_data <- All_Site_Combo %>% select(playentertain_2, structureactivities_2, selfcareadl_2, mealtimefood_2)
domain_data<-domain_data[complete.cases(domain_data),]

describe(domain_data)

cfa_model <- 'Adaptive_Func =~ selfcareadl_2 +structureactivities_2+mealtimefood_2 + playentertain_2' 

cfa_fit <- cfa(cfa_model, data = domain_data,
               ordered=c("selfcareadl_2", "structureactivities_2", "mealtimefood_2","playentertain_2"))

cfa_fit <- cfa(cfa_model, data = domain_data)

summary(cfa_fit, fit.measures = TRUE)

parameterEstimates(cfa_fit, standardized=TRUE) %>% 
  filter(op == "=~") %>% 
  mutate(stars = ifelse(pvalue < .001, "***", 
                        ifelse(pvalue < .01, "**", 
                               ifelse(pvalue < .05, "*", "")))) %>%
  select('Latent Factor'=lhs, 
         Indicator=rhs, 
         B=est, 
         SE=se, Z=z, 
         Beta=std.all, 
         sig=stars) %>% 
  kable(digits = 3, format="pandoc", caption=" Factor Loadings")

```


#Omega
```{r}

omega(domain_data)
```
